config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks',
                                    registrations: 'registrations'}

  root 'questions#index'

  concern :commentable do
    resources :comments, shallow: true, only: [:create]
  end

  resources :questions, except: [:edit] do
    concerns :commentable

    resources :answers, shallow: true, except: [:index, :show, :new] do
      post :mark_as_best, on: :member
      post :like, on: :member
      post :unlike, on: :member

      concerns :commentable
    end

    resources :subscriptions, only: [:create, :destroy]

    post :like, on: :member
    post :unlike, on: :member
  end
  resources :rewards, only: [:index]
  resources :attachments, only: [:destroy]
  resources :links, only: [:destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        resources :answers, shallow: true, only: [:index, :show, :create, :update, :destroy]
      end
    end
  end

  mount ActionCable.server => '/cable'
  get 'search', to: 'search#index'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_authorization_check

  def index
    @result = SearchService.new(params[:query], params[:scope]).call
  end
end

app/views/search/_answer.html.slim
p
  = 'Answer: '
  = link_to answer.body, question_path(answer.question)
p
  = 'Author: '
  = answer&.user&.email
  

app/views/search/_comment.html.slim
p
  = 'Comment: '
  = comment.body
p
  = 'Author: '
  = comment&.user&.email
  

app/views/search/_form.html.slim
= form_tag search_path, method: :get do
    = select_tag :scope, options_for_select(SearchService::TYPES, params[:scope])
    = text_field_tag :query, params[:query], placeholder: 'Search for:'
    = submit_tag 'Search'
  

app/views/search/_question.html.slim
p
  = 'Question: '
  = link_to question.title, question_path(question)
p
  = 'Body: '
  = question.body
p
  = 'Author: '
  = question&.user&.email
  

app/views/search/_user.html.slim
p
  = 'User: '
  = user&.email
  

app/views/search/index.html.slim
- if @result.any?
  - @result.each do |object|
    = render partial: "#{object.class.name&.downcase}", object: object
- else
  p = 'Nothing found'
  